In [1]:
#array operations 
import numpy as np


In [2]:
a=np.array([[10,23,32],[34,23,23]])

In [3]:
a

array([[10, 23, 32],
       [34, 23, 23]])

In [4]:
a[0]

array([10, 23, 32])

In [5]:
a[1]

array([34, 23, 23])

In [6]:
a[0][1]

23

In [7]:
#slicing
s=np.arange(10,100,10)

In [8]:
s

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
s[2:5]

array([30, 40, 50])

In [11]:
b=np.copy(a)

In [12]:
b

array([[10, 23, 32],
       [34, 23, 23]])

In [13]:
a,b

(array([[10, 23, 32],
        [34, 23, 23]]),
 array([[10, 23, 32],
        [34, 23, 23]]))

In [15]:
#view
c=b.view()

In [16]:
c

array([[10, 23, 32],
       [34, 23, 23]])

In [18]:
print("a=",a)
print("b=",b)
print("c=",c)

a= [[10 23 32]
 [34 23 23]]
b= [[10 23 32]
 [34 23 23]]
c= [[10 23 32]
 [34 23 23]]


In [21]:
a[0][2]=200

In [22]:
a

array([[ 10,  23, 200],
       [ 34,  23,  23]])

In [23]:
b

array([[10, 23, 32],
       [34, 23, 23]])

In [24]:
b[1][0]=78

In [25]:
b

array([[10, 23, 32],
       [78, 23, 23]])

In [26]:
c

array([[10, 23, 32],
       [78, 23, 23]])

In [41]:
#sort
a=np.array([20,20,50,40,50,60])


In [42]:
a

array([20, 20, 50, 40, 50, 60])

In [44]:
np.sort(a,axis=0)

array([20, 20, 40, 50, 50, 60])

In [45]:
a

array([20, 20, 50, 40, 50, 60])

In [47]:
a=np.arange(10,100,10)


In [48]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
p=a.reshape(3,3)

In [53]:
p

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [57]:
a=np.array([10,30,2])
b=np.array([20,30,48])

In [59]:
np.append(a,b).reshape(2,3)

array([[10, 30,  2],
       [20, 30, 48]])

In [60]:
a=np.array([10,30,2])
b=np.array([20,30,48])

In [66]:
np.insert(a,1,56)

array([10, 56, 30,  2])

In [72]:
np.delete(a,1)

array([10,  2])

In [75]:
import numpy as np
a=np.array([10,80,2])
b=np.array([90,30,48])

In [84]:
np.concatenate((a,b),axis=0)

array([10, 80,  2, 90, 30, 48])

In [86]:
res=np.stack((a,b))

In [87]:
res

array([[10, 80,  2],
       [90, 30, 48]])

In [88]:
res[0]

array([10, 80,  2])

res[1]

In [89]:
res[0][1]

80

In [90]:
res[1]

array([90, 30, 48])

In [94]:
np.stack((a,b),axis=1)

array([[10, 90],
       [80, 30],
       [ 2, 48]])

In [95]:
a

array([10, 80,  2])

In [96]:
b

array([90, 30, 48])

In [98]:
np.vstack((a,b))

array([[10, 80,  2],
       [90, 30, 48]])

In [99]:
np.hstack((a,b))

array([10, 80,  2, 90, 30, 48])

In [100]:
np.concatenate((a,b))

array([10, 80,  2, 90, 30, 48])

In [101]:
a

array([10, 80,  2])

In [102]:
b

array([90, 30, 48])

In [103]:
np.dstack((a,b))

array([[[10, 90],
        [80, 30],
        [ 2, 48]]])

In [113]:
import numpy as np
x=np.arange(10,100,10)

In [114]:
x

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [123]:
z=np.split(x,3)

In [126]:
z

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

In [127]:
print(z)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]


In [131]:
s1,s2,s3=np.split(x,3)

In [132]:
s1

array([10, 20, 30])

In [133]:
s2

array([40, 50, 60])

In [134]:
s3

array([70, 80, 90])

In [138]:
a=np.arange(10,120,20).reshape(2,3)

In [139]:
a

array([[ 10,  30,  50],
       [ 70,  90, 110]])

In [140]:
a

array([[ 10,  30,  50],
       [ 70,  90, 110]])

In [141]:
a

array([[ 10,  30,  50],
       [ 70,  90, 110]])

In [142]:
np.where(a==30)

(array([0], dtype=int64), array([1], dtype=int64))

In [143]:
np.where(a%5==0)

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [144]:
p=np.array([10,20,303,404,494,36])

In [145]:
p

array([ 10,  20, 303, 404, 494,  36])

In [148]:
np.searchsorted(p,[20])

array([1], dtype=int64)

In [149]:
np.searchsorted(p,[20,36])

array([1, 2], dtype=int64)

In [151]:
#add
a=np.array([10,20,30])
b=np.array([1,2,3])

In [153]:
np.add(a,b)

array([11, 22, 33])

In [155]:
np.subtract(a,b)

array([ 9, 18, 27])

In [159]:
np.multiply(a,b)

array([10, 40, 90])

In [161]:
np.divide(a,b)

array([10., 10., 10.])

In [162]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

In [165]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558])

In [166]:
a

array([10, 20, 30])

In [167]:
b

array([1, 2, 3])

In [168]:
np.array_equal(a,b)

False

In [169]:
a==b

array([False, False, False])

In [184]:
import numpy as np
s=np.array([10,20,36,47,58])

In [185]:
np.max(s)

58

In [186]:
np.min(s)

10

In [188]:
np.average(a)

20.0

In [189]:
np.mean(a)

20.0

In [190]:
np.median(a)

20.0

In [191]:
np.std(a)

8.16496580927726