In [2]:
import numpy as np

In [3]:
#initializing Arrays
#zeros
a=np.zeros(3)

In [4]:
print(a)

[0. 0. 0.]


In [17]:
np.zeros([2,4,3])


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
#full
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.full([2,3,4],21)

array([[[21, 21, 21, 21],
        [21, 21, 21, 21],
        [21, 21, 21, 21]],

       [[21, 21, 21, 21],
        [21, 21, 21, 21],
        [21, 21, 21, 21]]])

In [22]:
#random.rand
np.random.rand(2,3,2)

array([[[0.08175206, 0.06728604],
        [0.94944898, 0.06458861],
        [0.62678774, 0.64746055]],

       [[0.71388386, 0.80885744],
        [0.4522357 , 0.23687798],
        [0.93979153, 0.99723786]]])

In [26]:
#onces
np.ones ([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [34]:
#eye
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [2]:
import numpy as np

In [3]:
#Numerical Ranges
a=np.arange(20,29,1)

In [4]:
print(a)

[20 21 22 23 24 25 26 27 28]
