In [1]:
import numpy as np

In [32]:
P=np.array(([1, 2, 3],[1,2,3]))

In [4]:
P

array([1, 2, 3])

In [13]:
np.zeros((0,1))

array([], shape=(0, 1), dtype=float64)

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.full((3, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.rand(3, 4)

array([[0.16229639, 0.83039626, 0.72813758, 0.01087517],
       [0.67153359, 0.05007111, 0.78579684, 0.51989782],
       [0.93633292, 0.41109304, 0.97169158, 0.92079259]])

In [20]:
np.random.randn(3, 4)

array([[ 2.01617618,  0.06459696, -0.42054111, -0.47853557],
       [ 0.25213187,  0.31482859, -0.45707842, -1.60981041],
       [-0.23265753,  0.56389757, -1.36239706, -0.74756897]])

In [21]:
np.random.randint

<function RandomState.randint>

In [24]:
P.shape

(3,)

In [25]:
P.size

3

In [26]:
P.ndim

1

In [27]:
P.dtype

dtype('int32')

In [33]:
P.reshape((2,3))

array([[1, 2, 3],
       [1, 2, 3]])

In [34]:
P.flatten()

array([1, 2, 3, 1, 2, 3])

In [39]:
P[0, 1]#Access elements.


2

In [41]:
P[:, 1] #Slice arrays.


array([2, 2])

In [42]:
P[1:3, :] #Slice with ranges.

array([[1, 2, 3]])

In [45]:
R=np.array([1,3,5])

In [46]:
R

array([1, 3, 5])

In [50]:
print(P+R)

[[2 5 8]
 [2 5 8]]


In [51]:
P-R

array([[ 0, -1, -2],
       [ 0, -1, -2]])

In [52]:
P*R

array([[ 1,  6, 15],
       [ 1,  6, 15]])

In [53]:
P%R

array([[0, 2, 3],
       [0, 2, 3]])

In [54]:
P/R

array([[1.        , 0.66666667, 0.6       ],
       [1.        , 0.66666667, 0.6       ]])

In [55]:
P**2

array([[1, 4, 9],
       [1, 4, 9]])

In [57]:
np.sqrt(P)

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [58]:
np.exp(R)

array([  2.71828183,  20.08553692, 148.4131591 ])

In [59]:
np.log(P)

array([[0.        , 0.69314718, 1.09861229],
       [0.        , 0.69314718, 1.09861229]])

In [60]:
#aggregation functions 

In [67]:
import numpy as np
np.sum([P+R])

30

In [69]:
np.sum([P+R])

30

In [76]:
np.median([[P]])

2.0

In [79]:
np.std([R])

1.632993161855452

In [80]:
np.var(P)

0.6666666666666666

In [85]:
np.min(R)

1

In [86]:
np.max(R)

5

In [88]:
np.argmin(P)

0

In [91]:
np.argmax(P)

2

In [90]:
P

array([[1, 2, 3],
       [1, 2, 3]])

In [92]:
#linear algebra

In [93]:
np.dot(P,R)

array([22, 22])

In [94]:
np.matmul(P,R)

array([22, 22])

In [100]:
P+3

array([[4, 5, 6],
       [4, 5, 6]])

In [ ]:
P([P>1])#boolean type

In [ ]:
P.copy(["R"])

In [110]:
np.sort([R])

array([[1, 3, 5]])

In [112]:
np.argsort(R)

array([0, 1, 2], dtype=int64)

In [130]:
np.vstack((R))

array([[1],
       [3],
       [5]])

In [131]:
np.vstack(P)

array([[1, 2, 3],
       [1, 2, 3]])

In [132]:
np.hstack(P)

array([1, 2, 3, 1, 2, 3])

In [133]:
np.hstack(R)

array([1, 3, 5])

In [139]:
np.concatenate((R+P))

array([2, 5, 8, 2, 5, 8])

In [ ]:
np.split(R,2)

In [ ]:
np.array_split(arr, 3)

In [ ]:
np.tile(arr, (2, 3))

In [ ]:
np.repeat(arr, 3)

In [ ]:
np.unique(arr)

In [141]:
R.T

array([1, 3, 5])

In [142]:
np.transpose(R)

array([1, 3, 5])